### ISSUE TITLE
Unable To Send A Request For CSVEvaluator Through Postman

### ISSUE THREAD

**Issue by SushantVarshney** [openscoring/openscoring#16]
I am trying to run CSVEvaluator curl command through postman but it's not working as it always says NullPointerException when I didn't provide the output file path and if provided it doesn't write any output to that
Provide me the Http Call for the same from postman

**Comment by vruusmann** [comment]
Are you accessing the `/model${id}/csv` REST API endpoint directly, or via the `org.openscoring.client.CsvEvaluator` command-line application?

Also, please provide the full stack trace of this `NullPointerException` that you're seeing - is it a client-side or server-side problem? If it's a server-side problem, then it can be found in the Openscoring log file.

**Comment by vruusmann** [comment]
Are you seeing the same `NullPointerException`?
```
Caused by: java.lang.NullPointerException
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:210)
        at com.google.common.net.MediaType.parse(MediaType.java:596)
        at org.openscoring.service.ModelResource.evaluateCsv(ModelResource.java:290)
```

If so, then you need to add the `Content-Type` header to your request.

For example: `Content-type: text/plain; charset=UTF-8`

**Comment by SushantVarshney** [comment]
Yeah this is the same error when I am hitting the rest point but the issue is that when I am using the curl command from the command prompt then it is creating output.csv at desired location but when I am making the HTTP call through the browser I get the response as shown on the github but no output file is created at the desired location.

**Comment by vruusmann** [comment]
If you specify the `Content-type` header, then Openscoring will be able to identify and evaluate your input CSV document. The results CSV document is sent as response body. It is nicely visible in Postman results display.

If you're having trouble saving the results CSV document from Postman to a file in local filesystem, then you need to consult with Postman documentation. Clearly, Openscoring is doing its part correctly.
