### ISSUE TITLE
[Question] Config file to add admin roles?

### ISSUE THREAD

**Issue by manugarri** [openscoring/openscoring#20]
I am trying to update a model from outside the local network. Since I am not in localhost I am not an admin.

My question is, how can I override this, is there any option/configuration I can modify?

Thanks one more time.

**Comment by vruusmann** [comment]
JAX-RS component `NetworkSecurityContextFilter`, which is responsible for granting the "admin" role based on the IP address, takes a configuration option `trustedAddresses`. If this option is set, then it will override the default behaviour:
https://github.com/openscoring/openscoring/blob/master/openscoring-service/src/main/java/org/openscoring/service/NetworkSecurityContextFilter.java#L58-L65

For example:
```
networkSecurityContextFilter {
  trustedAddresses = ["127.0.0.1", "22.33.44.55"]
}
```

**Comment by manugarri** [comment]
Thanks, as usual :)
