### ISSUE TITLE
Model persistence through API

### ISSUE THREAD

**Issue by christophe-rannou** [openscoring/openscoring#21]
I want to gain persistence when deploying models on Openscoring and to this end I used the `--model-dir` option to activate auto-deployment. However I would like to have the models persist when deployed through the API directly.

Is this already supported ? If not I would like to add this feature. In the API 1.2.X the POST method to deploy a model is not part of the API anymore. Maybe it could be used as an alternate method to deploy a method in a persistent manner (by storing the pmml file locally in the pmml directory). Another solution could be to have a different endpoint such as `http://host/openscoring/persist/model`.

Thanks!

**Comment by vruusmann** [comment]
Model storage and versioning is available as a separate REST API.

**Comment by karims** [comment]
I cannot find which API does `Model storage and versioning`. Can you let me know?
