### ISSUE TITLE
Problem to create 'converter-executable-1.3-SNAPSHOT.jar'

### ISSUE THREAD

**Issue by Nate75015** [openscoring/openscoring#23]
Good morning everybody !

I wanted to know if somebody has ever been concerned by this problem ...

I wanted to follow this tutorial. For this reason I have modified my pom.xml, in order to generate the convert executable, which is below :

[pom.txt](https://github.com/openscoring/openscoring/files/1035789/pom.txt)

when I open a terminal and I write in the good file :
-mvn clean install
It seems there is no problem (No mistakes message).

But when I try to execute this commande, I have this message :

command : java -jar converter-executable-1.3-SNAPSHOT.jar --pkl-input pipeline.pkl.z --pmml-output pipeline.pmml

answer : aucun attribut manifest principal dans converter-executable-1.3-SNAPSHOT.jar.

Does anybody have the solution ? Thanks you very much ...

**Comment by vruusmann** [comment]
> I wanted to follow this tutorial.

This issue belongs to the [JPMML-SkLearn](https://github.com/jpmml/jpmml-sklearn) project.

> For this reason I have modified my pom.xml, in order to generate the convert executable:

If you build the JPMML-SkLearn project using `mvn clean install`, then you can find the executable JAR file as `target/converter-executable-1.3-SNAPSHOT.jar`.

> "aucun attribut manifest principal dans converter-executable-1.3-SNAPSHOT.jar."

The executable JAR file is typically generated using the [Apache Maven Shade plugin](https://maven.apache.org/plugins/maven-shade-plugin/). The name of the main class must be specified in the `META-INF/MANIFEST.MF` file as the `Main-Class` attribute. 

Here's an example: https://github.com/jpmml/jpmml-sklearn/blob/master/pom.xml#L180-L200

**Comment by Nate75015** [comment]
Thanks you very Much Vruusmann. I succeed :)
