### ISSUE TITLE
Mismatch in pkl and PMML model predictions

### ISSUE THREAD

**Issue by mukulameta-iquanti** [openscoring/openscoring#25]
We trained an xgboost model using sklearn2pmml
We used xgboost pacakage and XGBClassifier inside it and initiated with parameters.

Here's the code for that:
```
from sklearn2pmml import PMMLPipeline

#xgmodel is our model object that is initiated.
xg_pipeline = PMMLPipeline([("estimator", xg_model)])

xg_pipeline.fit(X_train,y_train)
from sklearn.externals import joblib
joblib.dump(xg_pipeline, "xg_pipeline.pkl.z", compress = 9)
```

We converted this pkl.z file to a PMML model and are using it with the Openscoring web service.
There is a slight difference in the Openscoring scores and the predictions we get in case we use a pkl model directly using sklearn joblib modules.

Appreciate any help.

**Comment by vruusmann** [comment]
Define "slight discrepancy", example?

There is a small systemic prediction error, which stems from the fact that XGBoost performs all numeric operations (eg. summing the scores of member decision tree models) using 32-bit floating point arithmetic operations, whereas PMML defaults to 64-bit floating point arithmetic. This can result in a relative and/or absolute prediction errors of up to `1e-5` (eg. depending on the magnitude of values, fifth or sixth decimal place).

This "math context" issue has been reported to the PMML working group:
http://mantis.dmg.org/view.php?id=179

The proposed "math context" extension attribute `x-mathContext` is implemented in JPMML-Model and JPMML-Evaluator library versions 1.3.7. As a result, the JPMML software stack should now be able to reproduce XGBoost predictions within 1 ULP.
