### ISSUE TITLE
Exposing ParamMartix Entity of Model - General Regression

### ISSUE THREAD

**Issue by mohammedayub44** [openscoring/openscoring#29]
I'm deploying the logistic model and in the details of model I don't see the beta values of the logit model. (They are in the [ParamMatrix Entity in PMML 4.2](http://dmg.org/pmml/v4-2-1/GeneralRegression.html#xsdElement_GeneralRegressionModel) ) 
Is there any way of exposing these in the returned JSON. ?

**Comment by vruusmann** [comment]
Why do you need them exposed? Do you want to use them as some sort of feature importance measure?

Openscoring is a high-level service, which is intended to hide such low-level details/complexity away from end users. If you want to see model schema (detailed description of input and results fields), please refer to the `GET /model/${id}` summary endpoint. If you want to use the model, please refer to the `POST /model/${id}` or `POST /model/${id}/csv` evaluation endpoints.

During evaluation, Openscoring matches input values with beta values, and gives you a final result value.

**Comment by vruusmann** [comment]
Exposing model implementation details via REST API is a bad idea. In this particular case, it would mean breaching at least two layers of abstraction.
