### ISSUE TITLE
Feature Request: option to disable networkSecurityContextFilter

### ISSUE THREAD

**Issue by snowch** [openscoring/openscoring#32]
I have just deployed OpenScoring as a Bluemix cloud foundry application.  Bluemix provides an API gateway that can sit in front of cloud foundry applications and perform authentication.  To get this working, I have cloned your repo and hardcoded my NetworkSecurityContext.java like to:

```
// boolean trusted = isTrusted(address);
boolean trusted = true; // move responsibility for auth to API
```

It would be desirable if I could do this via a configuration rather than patching, e.g.

```
networkSecurityContextFilter {
    // If you wish to push security to another tier (e.g. api layer) you can set disabled = true 
    // to prevent openscoring from authenticating requests requiring the admin role
    disabled = false

    // List of trusted IP addresses. An empty list defaults to all local network IP addresses.
    // A client that originates from a trusted IP address (as indicated by the value of the CGI variable REMOTE_ADDR) is granted the "admin" role.
    trustedAddresses = []
}
```

**Comment by vruusmann** [comment]
> It would be desirable if I could do this via a configuration rather than patching

But can't you do it via the configuration already?

By default, the `application.componentClasses` option registeres the `org.openscoring.service.NetworkSecurityContextFilter` JAX-RS component class. If you set this option to an empty list, then all Openscoring-level user authentication and authorization should be off:
https://github.com/openscoring/openscoring/blob/master/openscoring-service/src/main/resources/reference.conf#L4

The usage of configuration files is explained in the README file.

**Comment by snowch** [comment]
Ah, that makes sense now - thank you.  Unfortunately, it was not clear from the docs.  Maybe this could be documented more explicitly?

```
application {
	// List of JAX-RS Component class names that must be registered
	componentClasses = [
		"org.openscoring.service.NetworkSecurityContextFilter"
	]
}

modelRegistry {
	// List of Visitor class names that must be applied to the PMML class model object
	visitorClasses = []

	// Should the uploaded PMML documents be validated against the PMML XML Schema Definition (XSD) resource or not?
	// Validation is a one time operation that takes place during model deployment. It does not affect model evaluation or undeployment in any way.
	validate = false
}

// If you wish to disable the networkSecurityContextFilter, remove this class from the 
// componentClasses list in the application configuration above.
networkSecurityContextFilter {
	// List of trusted IP addresses. An empty list defaults to all local network IP addresses.
	// A client that originates from a trusted IP address (as indicated by the value of the CGI variable REMOTE_ADDR) is granted the "admin" role.
	trustedAddresses = []
}
```

**Comment by snowch** [comment]
I thought it would be useful to know where documentation was not clear?

**Comment by manugarri** [comment]
@vruusmann I agree with @snowch  that the Readme is not very clear on this matter, only mention of network is the line `By default, the "admin" role is granted to all HTTP requests that originate from the local network address.` which does not really explain it in depth.

Ideally there would be a way to disable NetworkSecurityContextFilter. One clear example I am facing is when trying to use openscoring inside a docker container (and call it from the host). I cant really build any jar since the ip will be changing with every user, and thus the host wont be able to be an admin.

**Comment by vruusmann** [comment]
@manugarri  Replying to portions of your comment that you have edited away.

> Ideally there would be a way to disable NetworkSecurityContextFilter.

Everything that can be controlled via the configuration file.

You are not supposed to run Openscoring in configuration-less mode. You are supposed to take `application.conf.sample`, remove the `.sample` suffix, and make organization-specific changes to it.

This is already explained in the README file.

> One clear example I am facing is when trying to use openscoring inside a docker container (and call it from the host). I cant really build any jar since the ip will be changing with every user, and thus the host wont be able to be an admin.

When setting up a Docker container, you should capture its IP, and write it down into current `application.conf` as the `networkSecurityContextFilter.trustedAddresses` property.

The idea is that `application.conf` can be generated/updated dynamically (eg. using Maven AntRun Plugin).

**Comment by manugarri** [comment]
Oh thanks, i actually posted a different issue with the question since It was a bit of a sidetracking

**Comment by manugarri** [comment]
> The idea is that application.conf can be generated/updated dynamically (eg. using Maven AntRun Plugin).

If I understood correctly, does that mean having to create a docker image with maven to build openscoring jar every single time you run a container?

**Comment by manugarri** [comment]
FYI, disabling **org.openscoring.service.NetworkSecurityContextFilter** makes open openscoring-service test to fail

```-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.openscoring.service.CsvUtilTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.086 sec - in org.openscoring.service.CsvUtilTest
Running org.openscoring.service.ModelResourceTest
Tests run: 2, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 1.774 sec <<< FAILURE! - in org.openscoring.service.ModelResourceTest
associationRulesShopping(org.openscoring.service.ModelResourceTest)  Time elapsed: 1.401 sec  <<< FAILURE!
java.lang.AssertionError: expected:<201> but was:<403>
        at org.openscoring.service.ModelResourceTest.deployForm(ModelResourceTest.java:168)
        at org.openscoring.service.ModelResourceTest.associationRulesShopping(ModelResourceTest.java:114)

decisionTreeIris(org.openscoring.service.ModelResourceTest)  Time elapsed: 0.146 sec  <<< FAILURE!
java.lang.AssertionError: expected:<201> but was:<403>
        at org.openscoring.service.ModelResourceTest.deploy(ModelResourceTest.java:148)
        at org.openscoring.service.ModelResourceTest.decisionTreeIris(ModelResourceTest.java:76)

Running org.openscoring.service.WebApplicationExceptionMapperTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in org.openscoring.service.WebApplicationExceptionMapperTest

Results :

Failed tests: 
  ModelResourceTest.associationRulesShopping:114->deployForm:168 expected:<201> but was:<403>
  ModelResourceTest.decisionTreeIris:76->deploy:148 expected:<201> but was:<403>

Tests run: 4, Failures: 2, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Openscoring ........................................ SUCCESS [  0.629 s]
[INFO] Openscoring Common ................................. SUCCESS [  1.249 s]
[INFO] Openscoring Client ................................. SUCCESS [  1.526 s]
[INFO] Openscoring Common GWT ............................. SUCCESS [  3.429 s]
[INFO] Openscoring Service ................................ FAILURE [  5.660 s]
[INFO] Openscoring Server ................................. SKIPPED
[INFO] Openscoring WebApp ................................. SKIPPED
```

**Comment by manugarri** [comment]
This also means that disabling NetworkSecurityContextFilter means not even services within the same network have admin access.

**Comment by vruusmann** [comment]
> FYI, disabling org.openscoring.service.NetworkSecurityContextFilter makes open openscoring-service test to fail

I can understand why people might want to disable `NetworkSecurityContextFilter` during deployment, but why disable it during build?

You can instruct Apache Maven to skip tests by specifying the `maven.test.skip` system propery:
```
$ mvn -Dmaven.test.skip=true clean install
```

Perhaps you should simply download pre-built Openscoring WAR file from from the Maven Central repository.

**Comment by manugarri** [comment]
I know skipping the tests is an option. However if disabling the tests becomes a necessity at build time then there is no point in having tests, isnt it?

I would gladly download Openscoring from maven, however my needs require some modifications (which I believe is one of the great things of this project, its simplicity).

**Comment by vruusmann** [comment]
What is the proposed solution? Sure, the "official release" could include other security context implementations such as `EverybodyIsAdminContextFilter`, but they cannot be the default one - it's easier to teach people how to disable things (by uncommenting existing configuration items) than to enable things (by adding new configuration items).
