### ISSUE TITLE
Unable to access Openscoring webapp through Nginx server when Openscoring is Running as Docker container

### ISSUE THREAD

**Issue by RamakrishnaAddanki** [openscoring/openscoring#34]
Hi 

I am using Openscoring webapp [war file] with tomcat and it is running inside container of Kubernetes and in between openscoring and host machine [from where i am accessing it through REST client]  we have nginx proxy server is running.So i am trying to access the openscoring through nginx and we are using pod ip of nginx in trusted address to talk to openscoring application. But i want to access that using host machine ip [that is visitor machine host ip]. i tried the solutions by removing that component class in the application.conf at least to access without security but no luck and  i tried by placing container ip in the application.conf still not able to access getting "user not authorized". so can anyone suggest me how to access this openscoring webapp through nginx proxy using host machine[Where REST client is running].

**Comment by RamakrishnaAddanki** [comment]
Hence got no response closing the issue

**Comment by vruusmann** [comment]
Frankly, your question had nothing to do with Openscoring. If you need advice about configuring containers and web servers, then you should ask your question at StackOverflow instead (be sure to tag it with appropriate `docker`, `kubernetes`, `nginx` labels).
