### ISSUE TITLE
Excess use of memory by pmml.gz files

### ISSUE THREAD

**Issue by abhianan** [openscoring/openscoring#36]
Hi,
  I have total 2116 pmml.gz files of 1.9 GB of size . When I deployed all files in one go on azure server , it takes 256 GB of memory to load all . But when i checked memory usage after one day it decreased to 120GB and it is decreasing exponentially day by day . Could you suggest me some fix so that i can save memory ?

Thank You for your help

**Comment by vruusmann** [comment]
Connect to a running JVM, and execute `System.gc()`.
