### ISSUE TITLE
tensorflow serving support

### ISSUE THREAD

**Issue by Debasish-Das-CK** [openscoring/openscoring#40]
If I create a model using jpmml-tensorflow can I score it using openscoring ? If there is no tensorflow serving integration yet, would love to contribute it while doing a benchmark with tensorflow-serving...

**Comment by vruusmann** [comment]
> If I create a model using jpmml-tensorflow can I score it using openscoring?

You can score any PMML document with Openscoring. You can generate this PMML document using the JPMML-TensorFlow library, or any other JPMML conversion library (eg. JPMML-R, JPMML-SkLearn, JPMML-SparkML, JPMML-XGBoost etc).

> If there is no tensorflow serving integration yet

There is no need for TensorFlow integration. All PMML documents are self-contained (ie. zero runtime dependencies).

**Comment by Debasish-Das-CK** [comment]
@vruusmann will try it out and let you know the perf compared to tensorflow serving...
