### ISSUE TITLE
Is there a configuration for enabling/disabling REST endpoints

### ISSUE THREAD

**Issue by DouglasBrunner** [openscoring/openscoring#43]
Hi,

I'm wondering if there is a configuration to disable specific HTTP methods (ex: PUT & DELETE)? We would only like to provide access for end-users to use the models but not to make any kind of modifications to the models. It seems like we can load the models from a directory and only update them when the application is redeployed. But this doesn't solve the access to PUT and DELETE methods issue.

If there is some documentation or a specific class you could point me to that would be appreciated. 

Thanks,

**Comment by vruusmann** [comment]
Openscoring requires the user to have a `admin` role before allowing access to `PUT`, `DELETE` and a few other "privileged" endpoints.

Please see the README file and configure your web server/container properly.
