### ISSUE TITLE
feature request: add deploy method - pip/docker

### ISSUE THREAD

**Issue by yairdata** [openscoring/openscoring#45]
current uber jar and war deployment may it difficult to deploy in a case of strict firm's security controls is in place (limited to regular maven coordinates /pip installation/docker image)

**Comment by vruusmann** [comment]
The Openscoring-Docker service is here: https://github.com/openscoring/openscoring-docker

The Openscoring-Python client library is already available in PyPI: https://pypi.org/project/openscoring

**Comment by yairdata** [comment]
thanks!
