### ISSUE TITLE
How to enable CORS for the Server

### ISSUE THREAD

**Issue by yashwanthmadaka24** [openscoring/openscoring#46]
How to enable Cross-Origin Policy Requests

I am getting the below error:

Access to XMLHttpRequest at 'http://localhost:8080/openscoring/model/Stroke' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by vruusmann** [comment]
See https://github.com/WolfEkk/openscoring/commit/80d44947693d8b257fa022f090835da825e3ef77
