### ISSUE TITLE
the lastest jar version 2.0 "xgbValue" is not defined

### ISSUE THREAD

**Issue by scuhugo** [openscoring/openscoring#47]
when I use the jar version 2.0 for the xgboost.pmml predict.There is an error "xgbValue" is not defined occur, but the jar 1.4.5 not

**Comment by vruusmann** [comment]
Closing as duplicate of https://github.com/openscoring/openscoring/issues/48

Issue 48 contains a fully reproducible code example, so I'll do my thinking there.
