### ISSUE TITLE
"message" : "Attribute with value RegressionTable@targetCategory=1 is not valid"

### ISSUE THREAD

**Issue by yashwanthmadaka24** [openscoring/openscoring#51]
When I am trying to do Model evaluation using POST /model/${id} in single prediction mode, I am getting the below error.

{
  "message" : "Attribute with value RegressionTable@targetCategory=1 is not valid"
}

The above error occurs only when my model is in logistic regression. The PMML files of decision tree and random forest are working fine, but I am getting this error only when my model is in logistic regression. 

Whats the reason for this error?

**Comment by vruusmann** [comment]
> Whats the reason for this error?

"Attribute is not valid" - the underlying JPMML-Evaluator library thinks that your logistic regression PMML file is poorly encoded. Specifically, one `RegressionTable` element refers to a target field category, which doesn't exist (according to the `/PMML/DataDictionary/DataField` element).

This exception is thrown here:
https://github.com/jpmml/jpmml-evaluator/blob/master/pmml-evaluator/src/main/java/org/jpmml/evaluator/regression/RegressionModelEvaluator.java#L160-L162

**Comment by yashwanthmadaka24** [comment]
> > Whats the reason for this error?
> 
> "Attribute is not valid" - the underlying JPMML-Evaluator library thinks that your logistic regression PMML file is poorly encoded. Specifically, one `RegressionTable` element refers to a target field category, which doesn't exist (according to the `/PMML/DataDictionary/DataField` element).
> 
> This exception is thrown here:
> https://github.com/jpmml/jpmml-evaluator/blob/master/pmml-evaluator/src/main/java/org/jpmml/evaluator/regression/RegressionModelEvaluator.java#L160-L162

When I tried with the same model file 3 months back, I was able to do it. But now, I am facing this error with the same file which worked perfectly fine before. How can I fix this error?

**Comment by vruusmann** [comment]
> When I tried with the same model file 3 months back

BS. This check has been there for ages.

> How can I fix this error?

Use a proper PMML conversion software. For example, anything from the JPMML family of libraries would be perfect.

Speaking about this specific file, then you can tweak the value of this one problematic `RegressionTable@targetCategory` attribute manually. You should already have the line number (in the log file).

**Comment by yashwanthmadaka24** [comment]
> > When I tried with the same model file 3 months back
> 
> BS. This check has been there for ages.
> 
> > How can I fix this error?
> 
> Use a proper PMML conversion software. For example, anything from the JPMML family of libraries would be perfect.
> 
> Speaking about this specific file, then you can tweak the value of this one problematic `RegressionTable@targetCategory` attribute manually. You should already have the line number (in the log file).

I had used the pyspark2pmml library(https://github.com/jpmml/pyspark2pmml) for my pmml conversion.
To what value should I tweak the value of that RegressionTable@targetCategory attribute?
