### ISSUE TITLE
How to define the model.version?

### ISSUE THREAD

**Issue by springtty** [openscoring/openscoring#52]
Hi, the request below show field called 'model.version', how to define the model.version？
how the openscoring manage the model version?

curl http://localhost:8080/openscoring/model/DecisionTreeIris
{
  "id" : "DecisionTreeIris",
  "miningFunction" : "classification",
  "summary" : "Tree model",
  "properties" : {
    "created.timestamp" : "2020-05-12T06:48:46.726+0000",
    "accessed.timestamp" : "2020-05-12T06:49:08.835+0000",
    "file.size" : 4306,
    "file.md5sum" : "2d4698076ed807308c5ae40563b70345",
    "model.version" : null
  },

**Comment by vruusmann** [comment]
> how to define the model.version？

A quick code search shows that this field is set based on the `Header@modelVersion` attribute:
https://github.com/openscoring/openscoring/blob/2.0.1/openscoring-service/src/main/java/org/openscoring/service/providers/ModelProvider.java#L135 and http://dmg.org/pmml/v4-3/Header.html

If you're looking to implement more advanced model versioning, then you should create a subclass of `org.openscoring.service.providers.ModelProvider`.
