### ISSUE TITLE
Derived field

### ISSUE THREAD

**Issue by alibek-galiyev** [openscoring/openscoring#56]
I have PMML with CatBoost model. There're some numerical and categorical fields. All mappings in categorical fields are mapped in PMML. But when I'm trying to get a score, I get the message:

`{
    "message": "Field \"employment_type_id_mapped\" is not defined"
}`

I'm sure, I'm sending all fields correctly, including `employment_type_id`.

**Comment by vruusmann** [comment]
> I have PMML with CatBoost model.

What software did you use for producing your PMML document? The JPMML family of converters doesn't support CatBoost, so it must be some third-party software.

> I'm sending all fields correctly, including `employment_type_id`.

Yes, you may be sending all the primary input values correctly, but your PMML document contains invalid/missing field references.

Here, your PMML document seems to contain the following transformation:
```
employment_type_id_mapped = f(employment_type_id)
```

If you open it in a text editor, then can you find a `DerivedField` element whose name is `employment_type_id_mapped`?

**Comment by vruusmann** [comment]
Closing as "invalid", because the end users is attempting to deploy an invalid PMML document here (invalid/missing derived field declarations).
