### ISSUE TITLE
openscoring -- deploying war file with --model-dir parameter on a server

### ISSUE THREAD

**Issue by ghost** [openscoring/openscoring#9]
I am using jenkins to deploy openscoring war file on Tomact in my server.I cannot deploy from my machine for security reasons and I want to use --model-dir parameter in order to define a pmml repository folder on the server, so I can deploy my models by copying them to the folder. Can you please advise how I can pass a parameter when deploying a war file on Tomcat?

**Comment by erezmta** [comment]
Is this feature of having the server deploy all models from a directory on the server side / URL, upon it's initialisation, planned ?

We need this too - as part of our server installation which we wish to be auto-scaling on AWS, thereby more then one server may be up, and controlling model deployments from the client side via the existing model deployer does not make sense for our use-case.

Thanks !
Erez

**Comment by vruusmann** [comment]
The auto-deployment directory is an undocumented feature of the Openscoring command-line (CLI) server application. There are some other undocumented features (eg. ability to co-deploy a rich web application frontend for Openscoring management and administrative purposes) - you will find them if you screen the source code of the Main application class for parameter fields that have been tagged as "hidden": [Main.java] (https://github.com/jpmml/openscoring/blob/master/openscoring-server/src/main/java/org/openscoring/server/Main.java)

In brief, you can tell Openscoring CLI server application to watch the specified directory for filesystem events by specifying the `--model-dir` command-line option:
```
java -jar target/server-executable-1.2-SNAPSHOT.jar --model-dir /path/to/pmmldir
```

A single model directory can be "watched" by any number of Openscoring instances. In case of a filesystem event (eg. a new PMML file is dropped into dir, or an existing PMML file is removed from the dir), then they will all receive and process filesystem events independently. Therefore, it is possible that "model set state" of Openscoring instances may be out of sync for a very brief time (perhaps 1 second), which should be a non-issue for most applications. If you want the state to be synced faster than that, then you must implement your own coordination layer.

**Comment by vruusmann** [comment]
It would be rather easy to manage the state of multiple Openscoring instances by "hiding" them behind HAProxy (or similar technology) and configuring the latter to:
* Propagating HTTP `PUT` and `DELETE` operations (ie. model deployment and undeployment requests) to all instances.
* Propagating HTTP `GET` operations (eg. model evaluation requests) only to a single instance.

**Comment by erezmta** [comment]
Thanks for the info. Indeed I saw the hidden parameters in the code. 

However, we are running open scoring on Tomcat. 
And we wish the war, upon deployment/initialization, to install our models. 
And we are behind AWS ELB in elastic beanstalk environment. It does not have the HAProxy features u mentioned.

**Comment by vruusmann** [comment]
It is possible to embed the `org.openscoring.client.DirectoryDeployer` component into the Openscoring WAR application as well. In that case you would use the Servlet configuration XML file (instead of the `--model-dir` command-line option) to specify the location of the auto-deployment directory.

The decision to make auto-deployment available for CLI application, and not for WAR application, has historical "reasons". Today, when the auto-deployment functionality has been successfully encapsulated into reusable `DirectoryDeployer` component, it is probably time to re-evaluate these.

I'll see what can be done in a day or two, and keep this issue updated.

**Comment by vruusmann** [comment]
No longer relevant in March 2019.
